### PR TITLE
Refactors

### PR DESCRIPTION
**Pull request by danny-avila**
delegating progress callback to its own file and same function across all routes

same with any text handling

fix migration code to account for old created date property

### CODE REVIEW

**Comment by danny-avila** [comment]
I will probably work on sanitize html after we merge to master. It wont be straightforward but simple enough because we can't blanket sanitize all situations

**Comment by wtlyu** [comment]
I have nothing else to be comment except that one. looks clear. 

If you think it's ok, you can merge by yourself.

(but I do think combine a nonsence `created` attribute is confusing..  It's never define without reading the full git history.)

**Comment by danny-avila** [comment]
> (but I do think combine a nonsence `created` attribute is confusing.. It's never define without reading the full git history.)

yeah unfortunately it's just an artifact from the old schema. without that line of code, it will render old messages in ascending order

**Comment by wtlyu** [comment]
I got it. you cannot change createdAt by hand.

better solution is use professional tools like https://github.com/seppevs/migrate-mongo
Database break is normal ,and we will face this again in future.

**Comment by wtlyu** [comment]
after thinking a while. I want to persuade you to give up. writing a dirty code can solve the problem but it's definitely not the end. you will find more breaking thing like this. forexample, how to preserve the old messages? their messagrId and parentMessageId are mass. how to deal with messages that not match the model conversationid?. the best answer is delete and rebuild the db.

Besides, it's 0.x version and any breaking changes are acceptable. Once you want to keep a regular official release, a professional migration system should be involved. I remembered that in Python django migration is a complete system to hold the version upgrade

**Comment by wtlyu** [comment]
you can see https://typeorm.io/migrations brings a migration system design. that maybe useful than mongoos i guess.

**Comment by danny-avila** [comment]
I don't disagree, we should definitely use a migration tool, it was more for the purpose of merging PR without too much interruption to those already using the project. Keeping conversation data, and being able to search it, is in large part what inspired me to make the clone. I don't have a lot of experience with db migrations but I'm using this as an opportunity to learn, potentially with mongoimport like you said. 

Right now, I'm focusing on identifying any more bugs/side-effects with the PR, and we can move on from there.

**Pull request merged**
